<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Company;

class Quotation extends Model
{
    use HasFactory;

    protected $fillable = [
        'inquiry_id',
        'unique_code',
        'quotation_title',
        'quotation_date',
        'customer_type',
        'customer_id',
        'gst_no',
        'pan_no',
        'company_name',
        'company_type',
        'nature_of_work',
        'city',
        'state',
        'scope_of_work',
        'address',
        'contact_person_1',
        'contact_number_1',
        'position_1',
        'contact_person_2',
        'contact_number_2',
        'position_2',
        'contact_person_3',
        'contact_number_3',
        'position_3',
        'contract_copy',
        'contract_details',
        'company_email',
        'company_password',
        'service_description',
        'service_quantity',
        'service_rate',
        'service_total',
        'service_contract_amount',
        'amc_start_date',
        'amc_amount',
        'project_start_date',
        'completion_time',
        'retention_time',
        'retention_amount',
        'retention_percent',
        'tentative_complete_date',
        'terms_description',
        'terms_quantity',
        'terms_rate',
        'terms_total',
        'terms_completion',
        'completion_terms',
        'terms_tentative_complete_date',
        'custom_terms_and_conditions',
        'prepared_by',
        'mobile_no',
        'own_company_name',
        'sample_management',
        'user_friendly_interface',
        'contact_management',
        'test_management',
        'employee_management',
        'lead_opportunity_management',
        'data_integrity_security',
        'recruitment_onboarding',
        'sales_automation',
        'reporting_analytics',
        'payroll_management',
        'customer_service_management',
        'inventory_management',
        'training_development',
        'integration_lab',
        'employee_self_service_portal',
        'marketing_automation',
        'regulatory_compliance',
        'analytics_reporting',
        'integration_crm',
        'workflow_automation',
        'integration_hr',
        'basic_cost_description',
        'basic_cost_quantity',
        'basic_cost_rate',
        'basic_cost_total',
        'basic_cost_total_amount',
        'additional_cost_description',
        'additional_cost_quantity',
        'additional_cost_rate',
        'additional_cost_total',
        'additional_cost_total_amount',
        'support_description',
        'support_quantity',
        'support_rate',
        'support_total',
        'support_total_amount',
    ];

    protected $casts = [
        'quotation_date' => 'date',
        'amc_start_date' => 'date',
        'project_start_date' => 'date',
        'tentative_complete_date' => 'date',
        'terms_tentative_complete_date' => 'date',
        'service_description' => 'array',
        'service_quantity' => 'array',
        'service_rate' => 'array',
        'service_total' => 'array',
        'terms_description' => 'array',
        'terms_quantity' => 'array',
        'terms_rate' => 'array',
        'terms_total' => 'array',
        'terms_completion' => 'array',
        'completion_terms' => 'array',
        'custom_terms_and_conditions' => 'array',
        'basic_cost_description' => 'array',
        'basic_cost_quantity' => 'array',
        'basic_cost_rate' => 'array',
        'basic_cost_total' => 'array',
        'additional_cost_description' => 'array',
        'additional_cost_quantity' => 'array',
        'additional_cost_rate' => 'array',
        'additional_cost_total' => 'array',
        'support_description' => 'array',
        'support_quantity' => 'array',
        'support_rate' => 'array',
        'support_total' => 'array',
        'service_contract_amount' => 'decimal:2',
        'amc_amount' => 'decimal:2',
        'retention_amount' => 'decimal:2',
        'retention_percent' => 'decimal:2',
        'basic_cost_total_amount' => 'decimal:2',
        'additional_cost_total_amount' => 'decimal:2',
        'support_total_amount' => 'decimal:2',
        'sample_management' => 'boolean',
        'user_friendly_interface' => 'boolean',
        'contact_management' => 'boolean',
        'test_management' => 'boolean',
        'employee_management' => 'boolean',
        'lead_opportunity_management' => 'boolean',
        'data_integrity_security' => 'boolean',
        'recruitment_onboarding' => 'boolean',
        'sales_automation' => 'boolean',
        'reporting_analytics' => 'boolean',
        'payroll_management' => 'boolean',
        'customer_service_management' => 'boolean',
        'inventory_management' => 'boolean',
        'training_development' => 'boolean',
        'integration_lab' => 'boolean',
        'employee_self_service_portal' => 'boolean',
        'marketing_automation' => 'boolean',
        'regulatory_compliance' => 'boolean',
        'analytics_reporting' => 'boolean',
        'integration_crm' => 'boolean',
        'workflow_automation' => 'boolean',
        'integration_hr' => 'boolean',
    ];

    public function inquiry()
    {
        return $this->belongsTo(Inquiry::class);
    }

    public function company()
    {
        return $this->belongsTo(Company::class, 'customer_id');
    }
}